name: Test

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:

  build:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        architecture: ['x64']

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: dependencies
        run: |
          python -m pip install -U pip wheel setuptools
      - name: wheel
        run: |
          python -m pip install -e .[tests]
      - name: flake8
        run: |
          flake8 pytiled_parser
      - name: mypy
        if: success() || failure()
        run: |
          mypy pytiled_parser
      - name: black
        if: success() || failure()
        run: |
          black pytiled_parser --check
      - name: pytest
        if: success() || failure()
        run: |
          pytest --cov=pytiled_parser --cov-report=xml --cov-report=html